#!/bin/bash

# redisd - Startup script for redisd

# chkconfig: 345 83 04
# description: Key Value Storage.
# processname: redisd
# config: /etc/redis.conf
# pidfile: /var/run/redisd/redisd.pid

. /etc/rc.d/init.d/functions

NAME="redisd"
CONFIGFILE="/etc/$NAME.conf"
OPTIONS="-c $CONFIGFILE"
LOCKFILEPATH=/var/lock/subsys/redisd
PIDFILEPATH=`awk -F'[:=]' -v IGNORECASE=1 '/^[[:blank:]]*pidfile[[:blank:]]*[:=][[:blank:]]*/{print $2}' "$CONFIGFILE" | tr -d '[:blank:]'`
redisd=${REDISD-/usr/local/bin/redisd}
USER=redisd

start() {
    echo -n $"Starting $NAME:"
    daemon --user "$USER" "$redisd $OPTIONS >/dev/null 2>&1"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILEPATH
}

stop() {
    echo -n $"Stopping $NAME: "
    killproc -p "$PIDFILEPATH" -d 10 $redisd
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILEPATH
}

restart() {
    stop
    start
}


RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  condrestart)
    [ -f $LOCKFILEPATH ] && restart || :
    ;;
  status)
    status $redisd
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac

exit $RETVAL