#!/bin/bash

# mqttd - Startup script for mqttd

# chkconfig: 345 83 04
# description: ...
# processname: mqttd
# config: /etc/mqttd.conf
# pidfile: /var/run/mqttd/mqttd.pid

. /etc/rc.d/init.d/functions

NAME="mqttd"
CONFIGFILE="/etc/$NAME.conf"
OPTIONS="-c $CONFIGFILE"
LOCKFILEPATH=/var/lock/subsys/mqttd
PIDFILEPATH=`awk -F'[:=]' -v IGNORECASE=1 '/^[[:blank:]]*pidfile[[:blank:]]*[:=][[:blank:]]*/{print $2}' "$CONFIGFILE" | tr -d '[:blank:]'`
mqttd=${MQTTD-/usr/local/bin/mqttd}
USER=mqttd

start() {
    echo -n $"Starting $NAME:"
    daemon --user "$USER" "$mqttd $OPTIONS >/dev/null 2>&1"
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILEPATH
}

stop() {
    echo -n $"Stopping $NAME: "
    $supervisorctl $OPTIONS shutdown >/dev/null 2>&1
    killproc -p "$PIDFILEPATH" -d 10 $mqttd
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $LOCKFILEPATH
}

restart() {
    stop
    start
}


RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  condrestart)
    [ -f $LOCKFILEPATH ] && restart || :
    ;;
  status)
    status $mqttd
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac

exit $RETVAL