;
(function (global, factory) {
    //MODULE EXPORTS
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
            //AMD MODULE
            typeof define === 'function' && define.amd ? define(factory) :
            //GLOBAL REFERENCE
            global.Menu = factory($, document);

})(this, function ($, document) {
    'use strict';

    /**
     * Class that handles the Menu behaviour.
     * @param {Object} categories Categories to render.
     * @constructor
     */
    var Menu = function (auto) {
        //CONSTANTS
        this.SELECTEDCLASS = "menu-selected";
        /**
         * Callback function that will be called upon selecting a category.
         * @protected
         * @type {number}
         */
        this.selectCallback = null;
        /**
         * List of all available categoires as pair of key-value.
         * @type {Object}
         * @protected
         */
        this.categories = {};
        /**
         * JQuery object that contains the available menu holders
         * @type {JQuery}
         * @protected
         */
        this.JQmenuHolder = $('ul[data-menu="categories"]');

        /**
         * Sets if there will be an auto-generated inside the selected
         * jQuery or if the menu will be rendered from the menu's items.
         */
        this.autoGenerated = auto;

        
        this.init();

    };

    //PROTO
    Menu.prototype = {
        /**
         * Inital sets
         * @private
         * @returns {undefined}
         */
        init: function () {
            if (!this.autogenerated) {
                var me = this;

                this.JQmenuHolder.each(function () {
                    $(this).children("li").each(function () {
                        me.setLiEvent($(this));
                    });
                });
            }
        },
        /**
         * This menu will render
         * @public
         * @returns {undefined}
         */
        addCatetories: function (categories) {
            if (this.autogenerated) {
                for (var i = 0; i < categories; i++) {
                    var cat = categories[i];
                    if (!this.categories[cat]) {
                        this.categories[cat] = true;

                        this.render(cat);
                    }
                }
            }
        },
        /**
         * Resets the current menu.
         * @public
         * @returns {undefined}
         */
        reset: function () {
            if (this.autoGenerated) {
                this.JQmenuHolder.children().remove();
                this.categories = {};
            }
        },
        /**
         * Sets a callback for the onselect event.
         * @param {function} cb Callback
         * @returns {undefined}
         */
        onSelect: function (cb) {
            this.selectCallback = cb;
        },
        /**
         * Initiates the menu element for each category.
         * @param {string} category Category to render.
         * @private
         * @returns {undefined}
         */
        render: function (category) {
            if (category) {
                var li = $(document.createElement("li"));
                var me = this;

                li.text(category);
                li.attr("data-categories", category);


                this.JQmenuHolder.append(li);

                this.setLiEvent(li);
            }
        },
        /**
         * Sets the event click on the li elements.
         * @param {jQuery} li
         * @returns {undefined}
         */
        setLiEvent: function (li) {
            var me = this;
            li.on("click.category", function () {
                var cl = $(this);
                var lis = me.JQmenuHolder.children("li");
                var data = cl.attr("data-categories");

                lis.removeClass(me.SELECTEDCLASS);
                cl.addClass(me.SELECTEDCLASS);

                me.selectCallback.call(me, data.split(","));
            });
        }
    };


    //FACTORY's FINAL OBJECT
    return Menu;
});
